#pragma once

#define DEVICE_SAMPLE_RATE 48000.0f
#define DEVICE_FORMAT ma_format_f32
#define OUTPUT_CHANNELS 2
#define INPUT_BIN_SIZE 2048 
#define RANDOM_PHASE 0
#define NORMALIZE_PEAK 1
#define BIN_DECIMATION_FACTOR 2
#define STFT_DECIMATION_FACTOR 2
#define ROLLOFF_THRESHOLD 0.85f
#define MFCC_COEFF_COUNT 12
